"use client";

import React, { useState } from "react";
import { LegalDocument, ChecklistItem } from "@/types/legal";
import { CheckSquare, Square, Download, Share2, Sparkles, Clock, CheckCircle } from "lucide-react";
import confetti from "canvas-confetti";
import { saveDocument } from "@/lib/storage/documentStore";

interface ChecklistTabProps {
  document: LegalDocument;
}

export const ChecklistTab: React.FC<ChecklistTabProps> = ({ document }) => {
  const [items, setItems] = useState<ChecklistItem[]>(document.analysis?.checklist || []);

  const handleToggle = async (id: string) => {
    const updated = items.map((item) => {
      if (item.id === id) {
        const nextState = !item.completed;
        if (nextState) {
          // Trigger confetti
          try {
            confetti({
              particleCount: 40,
              spread: 60,
              origin: { y: 0.8 },
            });
          } catch {
            // ignore
          }
        }
        return { ...item, completed: nextState };
      }
      return item;
    });

    setItems(updated);

    // Persist to document
    if (document.analysis) {
      document.analysis.checklist = updated;
      await saveDocument(document);
    }
  };

  const completedCount = items.filter((i) => i.completed).length;
  const progressPercent = items.length > 0 ? Math.round((completedCount / items.length) * 100) : 0;

  const handleExportText = () => {
    const content = `LEGAL ACTION CHECKLIST - ${document.title}
Generated by LegalClarity AI (${new Date().toLocaleDateString()})

Progress: ${completedCount} / ${items.length} tasks completed (${progressPercent}%)

TASKS:
${items
  .map(
    (item, idx) =>
      `[${item.completed ? "X" : " "}] ${idx + 1}. ${item.task}
      Category: ${item.category} | Due: ${item.dueWindow || "Before signing"} | Ref: ${item.sourceRef || "N/A"}`
  )
  .join("\n\n")}
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement("a");
    a.href = url;
    a.download = `${document.title.replace(/\s+/g, "_")}_Checklist.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white">
            Actionable Compliance & Verification Checklist
          </h3>
          <p className="text-xs text-slate-500">
            Convert long contractual provisions into a tangible step-by-step to-do list
          </p>
        </div>

        <button
          onClick={handleExportText}
          className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 shadow-sm hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
        >
          <Download className="h-3.5 w-3.5" />
          Export Checklist (.txt)
        </button>
      </div>

      {/* Progress Bar Card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="flex items-center justify-between text-xs">
          <span className="font-bold text-slate-700 dark:text-slate-300">Completion Progress</span>
          <span className="font-semibold text-indigo-600 dark:text-indigo-400">
            {completedCount} of {items.length} Tasks ({progressPercent}%)
          </span>
        </div>
        <div className="mt-2.5 h-2.5 w-full rounded-full bg-slate-100 overflow-hidden dark:bg-slate-800">
          <div
            className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-500 transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Checklist Items */}
      <div className="space-y-3">
        {items.map((item) => (
          <div
            key={item.id}
            onClick={() => handleToggle(item.id)}
            className={`flex cursor-pointer items-start gap-3.5 rounded-2xl border p-4.5 transition ${
              item.completed
                ? "border-emerald-200 bg-emerald-50/30 dark:border-emerald-900/40 dark:bg-emerald-950/20"
                : "border-slate-200 bg-white hover:border-slate-300 dark:border-slate-800 dark:bg-slate-900"
            }`}
          >
            <div className="mt-0.5 shrink-0">
              {item.completed ? (
                <CheckCircle className="h-5 w-5 text-emerald-600" />
              ) : (
                <div className="h-5 w-5 rounded-md border-2 border-slate-300 hover:border-indigo-500 dark:border-slate-600" />
              )}
            </div>

            <div className="flex-1 space-y-1">
              <p
                className={`text-xs sm:text-sm font-medium ${
                  item.completed
                    ? "text-slate-400 line-through dark:text-slate-500"
                    : "text-slate-900 dark:text-white"
                }`}
              >
                {item.task}
              </p>

              <div className="flex flex-wrap items-center gap-2 pt-1">
                <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                  {item.category}
                </span>

                {item.dueWindow && (
                  <span className="flex items-center gap-1 text-[10px] text-slate-500">
                    <Clock className="h-3 w-3" />
                    Due: {item.dueWindow}
                  </span>
                )}

                {item.sourceRef && (
                  <span className="text-[10px] text-indigo-600 dark:text-indigo-400 font-medium">
                    Ref: {item.sourceRef} (Page {item.pageNumber || 1})
                  </span>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
